### ISSUE TITLE
CSV support?

### ISSUE THREAD

**Issue by jackmaney** [krockode/x_x#11]
Since 99% of my use of Excel is as a CSV viewer anyway, would a PR be welcome to add support for rendering CSVs? In particular:

* The CLI could make a reasonable guess as to whether or not the file type is an Excel file or CSV by file extension.

* There can be optional, mutually exclusive `--csv` and `--excel` flags to force loading of the file as CSV or Excel, respectively.

* I believe most (if not all) of the internal changes would be confined to the `XCursor` class.

* For Python 2, [`unicodecsv`](https://github.com/jdunck/python-unicodecsv) can be used as a drop-in replacement for `csv` to handle CSVs with unicode (I think Python 3's `csv` already handles unicode).

**Comment by krockode** [comment]
Sounds like that would be useful!  You could probably even default to the file extention (*.csv assume csv, *.xsl* assume excel) and have the switches as overrides.

**Comment by jackmaney** [comment]
[Done](https://github.com/krockode/x_x/pull/12). I've manually tested it on Excel and CSV files on both 2.7.9 and 3.4.3.
